os:
  editCommand: 'code'
git:
  paging:
    colorArg: always -w
    pager: diff-so-fancy
  branchLogCmd: "git diff master..{{branchName}}"
  allBranchesLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline --"
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
customCommands:
  - key: 'o'
    command: 'open "https://stash.gto.intranet.db.com:8082/dashboard"'
    context: 'localBranches'