os:
  editCommand: 'code'
git:
  paging:
    colorArg: always -w
    pager: diff-so-fancy
  branchLogCmd: "git diff master..{{branchName}}"
  allBranchesLogCmd: "git log --all --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline --"
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
keybinding:
  universal:
    prevItem: null #override up/down to move commits in commits pane
    nextItem: null #override up/down to move commits in commits pane
  commits:
    moveDownCommit: '<down>' # move commit down one
    moveUpCommit: '<up>' # move commit up one
customCommands:
  - key: 'o'
    command: 'open "https://stash.gto.intranet.db.com:8082/dashboard"'
    context: 'localBranches'
  - key: 'u'
    prompts:
      - type: 'menu'
        title: 'Pick a command.'
        options:
          - name: 'assume-unchanged'
            description: 'Single selection'
            value: 'git update-index --assume-unchanged {{.SelectedFile.Name | quote}}'
          - name: 'list all assume-unchanged files'
            description: 'Global command'
            value: 'git ls-files -v | grep ''^[[:lower:]]''; false'
          - name: 'reset all assume unchanged files'
            description: 'Global command'
            value: 'git update-index --really-refresh; true'
    command: "{{index .PromptResponses 0}}"
    context: 'files'
    loadingText: '' 
    


# add command to push up to selected commit and keep later commits local
# How to expand staged pane to the maximum?