os:
  editCommand: 'code'
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip' | 'quit'
git:
  paging:
    colorArg: always
    pager: >
      delta 
      --dark 
      --paging=never
      --minus-style="normal #72202f"
      --plus-style="normal #004400"
      --plus-emph-style="normal #7fdb72"
      --minus-emph-style="normal #de9488"
  # old one with regular diff
  # branchLogCmd: "bash -c 'git diff $(git merge-base {{branchName}} origin/master) {{branchName}}'"
  # Experimental variants for better diff reviewing with --word-diff. Problem is that it is inconsistent and I cannot use the same in other panes.
  branchLogCmd: "bash -c 'git diff --word-diff=color $(git merge-base {{branchName}} origin/master) {{branchName}}'"
  allBranchesLogCmd: "git log --all --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline --"
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
keybinding:
  universal:
    prevItem: null #override up/down to move commits in commits pane
    nextItem: null #override up/down to move commits in commits pane
  commits:
    moveDownCommit: '<down>' # move commit down one
    moveUpCommit: '<up>' # move commit up one
customCommands:
  - key: 'o'
    command: 'open "https://stash.gto.intranet.db.com:8082/dashboard"'
    context: 'localBranches'
  - key: 'w'
    command: 'cd $(while [ ! -d ".bare" ]; do cd ..; done; pwd) && git worktree add {{.SelectedRemoteBranch.Name}} {{.SelectedRemoteBranch.Name}}'
    context: 'remoteBranches'
    showOutput: true
    prompts:
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to create workspace for {{.SelectedRemoteBranch.Name}} branch?"
  - key: 'u'
    context: 'files'
    loadingText: '...' 
    prompts:
      - type: 'menu'
        title: 'Pick a command.'
        options:
          - name: 'assume-unchanged'
            description: 'Single selection'
            value: 'git update-index --assume-unchanged {{.SelectedFile.Name | quote}}'
          - name: 'list all assume-unchanged files'
            description: 'Global command'
            value: 'git ls-files -v | grep ''^[[:lower:]]''; false'
          - name: 'reset all assume unchanged files'
            description: 'Global command'
            value: 'git update-index --really-refresh; true'
    command: "{{index .PromptResponses 0}}"
  - key: 'P'
    command: "git push {{.SelectedRemote.RefName}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.RefName}}"
    context: "commits"
    loadingText: "Pushing commit..."
    description: "Push a specific commit (and any preceding)"
    stream: yes   

# Switch places {} and []

# Assume unchanged reset and view should work even when no file is selected in
# files view. Right now they throw an error because SelectedFile.Name cannot be
# read for the "assume unchanged" command.

# Switch to delta as it can knows about the code structure and diff looks
# way better because of that (https://github.com/dandavison/delta)

# Add command to push up to selected commit and keep later commits local.

# How to expand staged pane to the maximum?

# Create worktree.

# Open associated JIRA.

# Open file in bitbucket with current line so I can share it easily.

# Find out what does "edit hunk" command do when I stage file line by
# line. It opens an editor with hunk, but how do I apply some changes?
# Nothing happens when I change something and save the file.

# Make lazygit keep its state with tmux in vscode? Else I  lose the context all
# the time when I open it once again. E.g. during a review when I need to move
# file by file.

# See extra commands here: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium