os:
  editCommand: 'code'
git:
  paging:
    colorArg: always -w
    pager: diff-so-fancy
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
customCommands:
  - key: 'o'
    command: 'open "https://stash.gto.intranet.db.com:8082/dashboard"'
    context: 'localBranches'