#! /bin/bash

code --install-extension achil.vscode-javascript-repl
code --install-extension alefragnani.numbered-bookmarks
code --install-extension AndenetAlexander.vim-cheatsheet
code --install-extension asvetliakov.vscode-neovim
code --install-extension bierner.docs-view
code --install-extension bodil.file-browser
code --install-extension dbaeumer.vscode-eslint
code --install-extension DominicVonk.auto-toggle-sidebar
code --install-extension eamodio.gitlens
code --install-extension edonet.vscode-command-runner
code --install-extension firsttris.vscode-jest-runner
code --install-extension geeebe.duplicate
code --install-extension GitWorktrees.git-worktrees
code --install-extension hdevalke.rust-test-lens
code --install-extension hediet.vscode-drawio
code --install-extension jacobdufault.fuzzy-search
code --install-extension jebbs.plantuml
code --install-extension kahole.magit
code --install-extension mhutchie.git-graph
code --install-extension MohammadBaqer.better-folding
code --install-extension nicoespeon.abracadabra
code --install-extension pixelbyte-studios.pixelbyte-love2d
code --install-extension PKief.material-icon-theme
code --install-extension pomdtr.excalidraw-editor
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension rust-lang.rust-analyzer
code --install-extension ryuta46.multi-command
code --install-extension s-nlf-fh.glassit
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vscode-snippet.snippet
code --install-extension VSpaceCode.vspacecode
code --install-extension VSpaceCode.whichkey
code --install-extension XadillaX.viml
code --install-extension zenclabs.previewjs
